In [2]:
import numpy as np

In [3]:
a = np.random.random((10,4))
a

array([[0.70470997, 0.50448454, 0.53717995, 0.68648482],
       [0.92260975, 0.85521964, 0.94730522, 0.69321214],
       [0.08801804, 0.73256   , 0.87341502, 0.00846701],
       [0.70627981, 0.10753168, 0.30378075, 0.39021463],
       [0.62683399, 0.13116923, 0.63027076, 0.81114861],
       [0.45189407, 0.55894617, 0.57717475, 0.05028312],
       [0.22081786, 0.40473378, 0.83864486, 0.74128717],
       [0.4277758 , 0.28516692, 0.04999983, 0.89918913],
       [0.72227385, 0.88931372, 0.34457675, 0.19695944],
       [0.22304749, 0.61438093, 0.50081179, 0.45374298]])

In [5]:
a.shape
a.size

40

In [6]:
b = np.random.random((5,2,3))
b

array([[[0.53244827, 0.39597683, 0.38884561],
        [0.15535272, 0.89543756, 0.59114409]],

       [[0.95127244, 0.62845783, 0.66943063],
        [0.17989253, 0.75224305, 0.13226314]],

       [[0.93708231, 0.59760626, 0.35068883],
        [0.65027817, 0.20618415, 0.28932419]],

       [[0.35475681, 0.23248333, 0.03848599],
        [0.33180929, 0.38471221, 0.84482296]],

       [[0.41326982, 0.19787992, 0.60277994],
        [0.4213858 , 0.54119774, 0.45374046]]])

In [7]:
c = np.random.random((2,3,4,5))
c

array([[[[0.03996662, 0.6625702 , 0.69125417, 0.44652611, 0.73642369],
         [0.0510128 , 0.77323674, 0.06566515, 0.60639289, 0.09661563],
         [0.09013303, 0.63805982, 0.33575884, 0.87477831, 0.99287947],
         [0.1127083 , 0.87082895, 0.30725884, 0.07620631, 0.0104868 ]],

        [[0.84120525, 0.22358266, 0.52503566, 0.08392257, 0.11446603],
         [0.71370024, 0.5863641 , 0.18505915, 0.21115858, 0.0376272 ],
         [0.6321953 , 0.59033846, 0.85756972, 0.45941051, 0.10509766],
         [0.02856338, 0.78495441, 0.94360178, 0.67826783, 0.85615197]],

        [[0.71516661, 0.35177913, 0.01860014, 0.20233982, 0.19405729],
         [0.07900931, 0.54995893, 0.82920581, 0.61692425, 0.87846933],
         [0.41465954, 0.3523467 , 0.69940754, 0.88017355, 0.51477935],
         [0.75307062, 0.98067365, 0.22554411, 0.27188954, 0.72356156]]],


       [[[0.93500648, 0.28269639, 0.6603542 , 0.35031449, 0.46504076],
         [0.07738953, 0.19864452, 0.86689974, 0.90468224, 0.72269994]

In [11]:
a[0]
a[:,0]
a[4,2]

0.6302707611927323

In [12]:
c[0]

array([[[0.03996662, 0.6625702 , 0.69125417, 0.44652611, 0.73642369],
        [0.0510128 , 0.77323674, 0.06566515, 0.60639289, 0.09661563],
        [0.09013303, 0.63805982, 0.33575884, 0.87477831, 0.99287947],
        [0.1127083 , 0.87082895, 0.30725884, 0.07620631, 0.0104868 ]],

       [[0.84120525, 0.22358266, 0.52503566, 0.08392257, 0.11446603],
        [0.71370024, 0.5863641 , 0.18505915, 0.21115858, 0.0376272 ],
        [0.6321953 , 0.59033846, 0.85756972, 0.45941051, 0.10509766],
        [0.02856338, 0.78495441, 0.94360178, 0.67826783, 0.85615197]],

       [[0.71516661, 0.35177913, 0.01860014, 0.20233982, 0.19405729],
        [0.07900931, 0.54995893, 0.82920581, 0.61692425, 0.87846933],
        [0.41465954, 0.3523467 , 0.69940754, 0.88017355, 0.51477935],
        [0.75307062, 0.98067365, 0.22554411, 0.27188954, 0.72356156]]])

In [13]:
# Second subgroup of the first group
c[0,1]

array([[0.84120525, 0.22358266, 0.52503566, 0.08392257, 0.11446603],
       [0.71370024, 0.5863641 , 0.18505915, 0.21115858, 0.0376272 ],
       [0.6321953 , 0.59033846, 0.85756972, 0.45941051, 0.10509766],
       [0.02856338, 0.78495441, 0.94360178, 0.67826783, 0.85615197]])

In [14]:
# Third row of the second subgroup
c[0,1,2]

array([0.6321953 , 0.59033846, 0.85756972, 0.45941051, 0.10509766])

In [15]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# Sum of all elements in matrix a
np.sum(a)

20.71191600275386

In [17]:
# Sum of each column in matrix a
np.sum(a, axis=0)

array([5.09426064, 5.08350662, 5.60315969, 4.93098906])

In [18]:
# Sum of each row in matrix a
np.sum(a, axis=1)

array([2.43285928, 3.41834676, 1.70246006, 1.50780688, 2.1994226 ,
       1.63829811, 2.20548368, 1.66213168, 2.15312377, 1.79198319])

In [19]:
# Sum of all the elements in the first two groups of array b
np.sum(b[:2])

6.272764677736507

In [23]:
# Mean of all elements in matrix a
np.mean(a)
# Mean of each column in matrix a
np.mean(a, axis=0)
# Mean of each row in matrix a
np.mean(a, axis=1)
# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

0.5227303898113757

In [25]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [26]:
x = np.ones((1, 2, 3))
x

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
np.transpose(x, (1, 0, 2)).shape
(2, 1, 3)

(2, 1, 3)